language: bash
services: docker

env:
  - VERSION=7.0 VARIANT=stretch/3.3.1
  - VERSION=7.2 VARIANT=stretch/3.4.0

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="matricali/phalcon:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
